# Generated by Django 3.1.4 on 2021-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20210114_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='goodtext',
            field=models.TextField(blank=True, default='a', null=True),
        ),
    ]
