# Generated by Django 3.1.4 on 2021-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_boardmodel_goodtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='goodtext',
            field=models.TextField(blank=True, default='->', null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='readtext',
            field=models.TextField(blank=True, default='->', null=True),
        ),
    ]
